/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazAdministrador;

import ProgramacionAcciones.agregarcliente_bd;
import javax.swing.JOptionPane;

/**
 *
 * @author danie
 */
public class agregar_cliente extends javax.swing.JPanel {

    public String adress;
    public static agregarcliente_bd acbd;
    /**
     * Creates new form agregar_cliente
     */
    public agregar_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ciun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        apellidom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        apellidop = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        calle = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        colonia = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        numint = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        numext = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ciudad = new javax.swing.JTextArea();
        snint = new javax.swing.JCheckBox();
        snext = new javax.swing.JCheckBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregado de cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 765, 42));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Codigo de Identificacion Unico de Negocio (CIUN)");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        ciun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ciun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciunActionPerformed(evt);
            }
        });
        add(ciun, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 337, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Nombre(s) de cliente");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        apellidom.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        apellidom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidomActionPerformed(evt);
            }
        });
        add(apellidom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 337, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Calle");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Apellido Paterno");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        apellidop.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        add(apellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 320, -1));

        nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 337, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        calle.setColumns(20);
        calle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        calle.setRows(5);
        jScrollPane1.setViewportView(calle);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 340, 40));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setText("Datos de negocio");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setText("Coloca los datos solicitados para realizar el agregado de un nuevo cliente");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 680, -1));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setText("Agregar cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 210, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setText("Datos personales");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("Colonia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        colonia.setColumns(20);
        colonia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        colonia.setRows(5);
        jScrollPane2.setViewportView(colonia);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 310, 40));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("Numero interior");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        numint.setColumns(20);
        numint.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        numint.setRows(5);
        jScrollPane3.setViewportView(numint);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 340, 40));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("Numero Exterior");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        numext.setColumns(20);
        numext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        numext.setRows(5);
        jScrollPane4.setViewportView(numext);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 310, 40));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setText("Ciudad");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        ciudad.setColumns(20);
        ciudad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        ciudad.setRows(5);
        jScrollPane5.setViewportView(ciudad);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 310, 40));

        snint.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        snint.setText("S/N");
        snint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snintActionPerformed(evt);
            }
        });
        add(snint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        snext.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        snext.setText("S/N");
        snext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snextActionPerformed(evt);
            }
        });
        add(snext, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public boolean verificar(){
        String txtnombre=nombre.getText();
        String txtapp=apellidop.getText();
        String txtapm=apellidom.getText();
        String txtciun=ciun.getText().toUpperCase();
        String txtciudad=ciudad.getText();
        String txtcalle=calle.getText();
        String txtcolonia=colonia.getText();
        String txtnumint=numint.getText();
        String txtnumext=numext.getText();
        //verificamos que no exista ningun campo vacio
        if(txtnombre.isEmpty()||txtapp.isEmpty()||txtapm.isEmpty()||txtciun.isEmpty()||txtciudad.isEmpty()
                ||txtcalle.isEmpty()||txtcolonia.isEmpty()||txtnumint.isEmpty()||txtnumext.isEmpty()){
            JOptionPane.showMessageDialog(null, "Coloque todos los datos solicitados","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //verificamos que el nombre y apellidos solo sean letras
        boolean vernom=txtnombre.matches("^[a-zA-Z ]*$");
        boolean verapp=txtapp.matches("^[a-zA-Z ]*$");
        boolean verapm=txtapm.matches("^[a-zA-Z ]*$");
        if(!vernom || !verapp || !verapm){
            JOptionPane.showMessageDialog(null, "Solo se permiten letras y espacios en el apartado"
                    + "\n de datos personales","Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //verificamos que el ciun sea solo numeros y letras sin espacios
        boolean resciun=txtciun.matches("[a-zA-Z0-9]+");
        if(!resciun){
            JOptionPane.showMessageDialog(null, "Solo ingresar letras y numeros como CIUN","ERROR",JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        //
        //verificamos que los datos de direccion sean correctos
        boolean verciu=txtciudad.matches("^[a-zA-Z ]*$");
        boolean vercalle=txtcalle.matches("^[a-zA-Z0-9 ]*$");
        boolean vercolonia=txtcolonia.matches("^[a-zA-Z0-9 ]*$");
        
        //verificamos que la ciudad solo sean numeros
        if(!verciu){
            JOptionPane.showMessageDialog(null, "Solo colocar letras en el apartado Ciudad","ERROR",JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        //verificamos que solo haya letras y numeros en calle y colonia
        if(!vercalle||!vercolonia){
            JOptionPane.showMessageDialog(null, "Solo ingresar letras y numeros en "
                    + "\n los apartados de Calle y Colonia","ERROR",JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        //verificamos los estados de numero interior y exterior
        if(!snint.isSelected()){
            boolean vernumint=txtnumint.matches("[0-9]+")&&Integer.parseInt(txtnumint)>0;
            if(!vernumint){
                JOptionPane.showMessageDialog(null, "Solo colocar numeros mayores a cero en el "
                        + "\n apartado de Numero interior","ERROR",JOptionPane.ERROR_MESSAGE); 
            return false;
            }
        }
        
        if(!snext.isSelected()){
            boolean vernumext=txtnumext.matches("[0-9]+")&&Integer.parseInt(txtnumext)>0;
            if(!vernumext){
                JOptionPane.showMessageDialog(null, "Solo colocar numeros mayores a cero en el "
                        + "\n apartado de Numero Exterior","ERROR",JOptionPane.ERROR_MESSAGE); 
            return false;
            }
        }
        //
        //verificamos que el niun no este registrado en la bd
        acbd = new agregarcliente_bd();
        if(acbd.verificar_ciun(txtciun)){
            JOptionPane.showMessageDialog(null, "El CIUN ingresado ya existe","ERROR",JOptionPane.ERROR_MESSAGE); 
            return false;
        }
        
        
        
        adress="Calle "+txtcalle+", Col. "+txtcolonia+", Int. "+txtnumint+", Ext. "+txtnumext+", "+txtciudad;
        return true;
    }
    
    
    
    private void apellidomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidomActionPerformed

    private void ciunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciunActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(verificar()){
            int opc;
            opc=JOptionPane.showConfirmDialog(null, "¿Todos los datos ingresados son correctos?"
                    , "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
            if(opc==0){
                acbd=new agregarcliente_bd();
                acbd.nuevo_registro(ciun.getText().toUpperCase(), nombre.getText(), apellidop.getText()
                , apellidom.getText(), adress);
                agregar_cliente ac = new agregar_cliente();
            }
        //System.out.println(adress);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void snintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snintActionPerformed
        if(snint.isSelected()){
            numint.setText("S/N");
            numint.setEditable(false);
        }else{
            numint.setText("");
            numint.setEditable(true);
        }
    }//GEN-LAST:event_snintActionPerformed

    private void snextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snextActionPerformed
        if(snext.isSelected()){
            numext.setText("S/N");
            numext.setEditable(false);
        }else{
            numext.setText("");
            numext.setEditable(true);
        }
    }//GEN-LAST:event_snextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidom;
    private javax.swing.JTextField apellidop;
    private javax.swing.JTextArea calle;
    private javax.swing.JTextArea ciudad;
    private javax.swing.JTextField ciun;
    private javax.swing.JTextArea colonia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextArea numext;
    private javax.swing.JTextArea numint;
    private javax.swing.JCheckBox snext;
    private javax.swing.JCheckBox snint;
    // End of variables declaration//GEN-END:variables
}
