/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazAdministrador;

import ProgramacionAcciones.eliminarcliente_bd;
import java.awt.Point;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author danie
 */
public class eliminar_cliente extends javax.swing.JPanel {

    public eliminarcliente_bd ecbd;
    
    /**
     * Creates new form eliminar_cliente
     */
    public eliminar_cliente() {
        initComponents();
        String tipo;
        tipo=(String) tipobusc.getSelectedItem();
        tipo=tipo.toLowerCase();
        ecbd=new eliminarcliente_bd();
        tabla.setModel(ecbd.mostrar_tabla("",tipo));
        //Le damos un mayor tamaño a la columna 2 que contiene las direcciones de los clientes
        tabla.getColumnModel().getColumn(5).setPreferredWidth(270);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        niuc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        barrabusc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        app = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        ciun = new javax.swing.JTextField();
        tipobusc = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setText("NIUC");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        niuc.setEditable(false);
        niuc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        niuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niucActionPerformed(evt);
            }
        });
        add(niuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setText("Direccion");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 80, -1));

        barrabusc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        barrabusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barrabuscActionPerformed(evt);
            }
        });
        barrabusc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barrabuscKeyPressed(evt);
            }
        });
        add(barrabusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        app.setEditable(false);
        app.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        add(app, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 170, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setText("Apellido paterno");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        nombre.setEditable(false);
        nombre.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, -1));

        apm.setEditable(false);
        apm.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        add(apm, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 180, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Apellido materno");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Buscar");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        direccion.setEditable(false);
        direccion.setColumns(20);
        direccion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        direccion.setRows(5);
        jScrollPane1.setViewportView(direccion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 540, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 700, 170));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("CIUN");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, -1));

        ciun.setEditable(false);
        ciun.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        add(ciun, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));

        tipobusc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        tipobusc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIUC", "CIUN" }));
        tipobusc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipobuscItemStateChanged(evt);
            }
        });
        tipobusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipobuscActionPerformed(evt);
            }
        });
        add(tipobusc, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 100, -1));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 190, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Proceso de eliminación de cliente");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 740, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Seleccione al cliente que desea eliminar");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 700, 20));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setText("Buscar por");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 90, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("Clientes");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void niucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niucActionPerformed

    private void barrabuscKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barrabuscKeyPressed
        niuc.setText("");
        ciun.setText("");
        nombre.setText("");
        app.setText("");
        apm.setText("");
        direccion.setText("");
        String txt=barrabusc.getText();
        int codevt;
        String ascii;
        codevt=evt.getKeyCode();

        //Realiza la transformacion de la tecla pulsada del codigo ascii a caracter
        //solo se activa si el codigo ascii corresponde a un caracter imprimible
        if(evt.getKeyCode()>31&&evt.getKeyCode()<126){
            ascii=Character.toString(evt.getKeyCode());
           // System.out.println(ascii);
            txt+=ascii;
        }else{
            if(evt.getKeyCode()==8&&barrabusc.getText().length()>0){
                //System.out.println("cumple retro"+evt.getKeyCode());
                txt=txt.substring(0,txt.length()-1);
            }else{
                if(evt.getKeyCode()==8){
                    txt="";
                }

            }
        }
        
        String tipo;
        tipo=(String) tipobusc.getSelectedItem();
        tipo=tipo.toLowerCase();
        ecbd=new eliminarcliente_bd();
        tabla.setModel(ecbd.mostrar_tabla(txt,tipo));
        //Le damos un mayor tamaño a la columna 2 que contiene las direcciones de los clientes
        tabla.getColumnModel().getColumn(5).setPreferredWidth(270);
    }//GEN-LAST:event_barrabuscKeyPressed

    private void tipobuscItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipobuscItemStateChanged
        //se vacian los JTextField para evitar errores
        niuc.setText("");
        ciun.setText("");
        nombre.setText("");
        app.setText("");
        apm.setText("");
        direccion.setText("");
        //Obtenemos el nuevo tipo seleccionado en el combobox y lo hacemos string
        String tipo;
        tipo=(String) tipobusc.getSelectedItem();
        tipo=tipo.toLowerCase();
        //obtenemos la string de la barra de busqueda
        String txt=barrabusc.getText();
        /**
        * Hacemos un objeto de la clase importada eliminarcliente_bd
        *
        * Seguido realizamo la llamda de la funcion mostrar_tabla de la clase y se le da el texto
        * de la barra de busqueda , el tipo de busqueda y el niue del empleado
        *
        * Esta funcion regresa un DefaultModelTable con los resultados de la busqueda en la base de datos
        * y lo coloca en la JTable tabla
        */
        ecbd=new eliminarcliente_bd();
        tabla.setModel(ecbd.mostrar_tabla(txt,tipo));
        //Le damos un mayor tamaño a la columna 2 que contiene las direcciones de los clientes
        tabla.getColumnModel().getColumn(5).setPreferredWidth(270);
    }//GEN-LAST:event_tipobuscItemStateChanged

    private void tipobuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipobuscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipobuscActionPerformed

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        JTable table=(JTable) evt.getSource();
                Point point=evt.getPoint();
                int row = table.rowAtPoint(point);
                
                if(evt.getClickCount()==1){
                    String nom,apep,apem;
                    
                    
                    //Coloca los datos de la tabla en los JTextField correspondientes
                    niuc.setText(tabla.getValueAt(tabla.getSelectedRow(), 0).toString());
                    ciun.setText(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
                    nombre.setText(tabla.getValueAt(tabla.getSelectedRow(), 2).toString());
                    app.setText(tabla.getValueAt(tabla.getSelectedRow(), 3).toString());
                    apm.setText(tabla.getValueAt(tabla.getSelectedRow(), 4).toString());
                    direccion.setText(tabla.getValueAt(tabla.getSelectedRow(), 5).toString());
                    //System.out.println(name+"  "+ln+"   "+city+"   "+np);
                }
    }//GEN-LAST:event_tablaMousePressed

    private void barrabuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrabuscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrabuscActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(niuc.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Seleccione primero un cliente","ERROR",JOptionPane.ERROR_MESSAGE);
            
        }else{
           int opc;
           opc = JOptionPane.showConfirmDialog(null, "¿DESEA ELIMINAR EL CLIENTE CON UN NIUC "+niuc.getText()+ "?","ADVERTENCIA",JOptionPane.YES_NO_OPTION);
           if(opc==0){
               ecbd=new eliminarcliente_bd();
               ecbd.eliminar(niuc.getText());
               eliminar_cliente ec = new eliminar_cliente();
           }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apm;
    private javax.swing.JTextField app;
    private javax.swing.JTextField barrabusc;
    private javax.swing.JTextField ciun;
    private javax.swing.JTextArea direccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField niuc;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tipobusc;
    // End of variables declaration//GEN-END:variables
}
